[build]
  base = "client"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://truenumber-production.up.railway.app/api"

# Redirections pour Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200