[build]
  base = "client"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200