[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'Building TrueNumber API...'"]

[start]
cmd = "cd server && node index.js"