[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm install --production']

[phases.build]
cmds = ['echo "TrueNumber API ready for deployment"']

[start]
cmd = 'node railway-debug.js'