[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd server && npm install --production']

[phases.build]
cmds = ['echo "Backend ready for deployment"']

[start]
cmd = 'cd server && node railway-start.js'